-- phpMyAdmin SQL Dump
-- version 4.8.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 18, 2020 at 09:15 AM
-- Server version: 10.1.34-MariaDB
-- PHP Version: 7.2.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cobaanime`
--

-- --------------------------------------------------------

--
-- Table structure for table `anime`
--

CREATE TABLE `anime` (
  `idanime` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `episodes` int(11) NOT NULL,
  `status` varchar(255) NOT NULL,
  `aired` date NOT NULL,
  `premiered` varchar(255) NOT NULL,
  `studios` varchar(255) NOT NULL,
  `source` varchar(255) NOT NULL,
  `genres` varchar(255) NOT NULL,
  `duration` int(11) NOT NULL,
  `score` float NOT NULL,
  `sinopsis` text NOT NULL,
  `gambar` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `anime`
--

INSERT INTO `anime` (`idanime`, `title`, `type`, `episodes`, `status`, `aired`, `premiered`, `studios`, `source`, `genres`, `duration`, `score`, `sinopsis`, `gambar`) VALUES
(65, 'Black Clover', 'tv', 155, 'ongoing', '2017-10-03', 'fall', 'C2C', 'Manga', 'comedy,fantasy,magic,shounen,action', 20, 7.3, 'Asta dan Yuno ditinggalkan di gereja yang sama pada hari yang sama. Dibesarkan bersama sebagai anak-anak, mereka mengenal &quot;Raja Penyihir&quot; Ã¢â‚¬â€sebuah gelar yang diberikan kepada penyihir terkuat di kerajaan Ã¢â‚¬â€ dan berjanji bahwa mereka akan bersaing satu sama lain untuk posisi Raja Penyihir berikutnya. Namun, saat mereka dewasa, perbedaan mencolok di antara mereka menjadi jelas. Sementara Yuno mampu menggunakan sihir dengan kekuatan dan kendali yang luar biasa, Asta tidak dapat menggunakan sihir sama sekali dan mati-matian berusaha membangkitkan kekuatannya dengan melatih secara fisik.\r\n\r\nKetika mereka mencapai usia 15, Yuno dianugerahi Grimoire yang spektakuler dengan semanggi berdaun empat, sementara Asta tidak menerima apa-apa. Namun, segera setelah itu, Yuno diserang oleh seseorang bernama Lebuty, yang tujuan utamanya adalah untuk mendapatkan Grimoire milik Yuno. Asta mencoba melawan Lebuty, tetapi dia kalah. Meskipun tanpa harapan dan di ambang kekalahan, dia menemukan kekuatan untuk melanjutkan ketika dia mendengar suara Yuno. Melepaskan emosi batinnya dengan marah, Asta menerima Grimoire semanggi berdaun lima, sebuah &quot;Semanggi Hitam&quot; yang memberinya kekuatan yang cukup untuk mengalahkan Lebuty. Beberapa hari kemudian, kedua sahabat itu pergi ke dunia, keduanya mencari tujuan yang sama menjadi Raja Penyihir!', 'black clover.jpg'),
(66, 'Yakusoku no Neverland', 'tv', 12, 'finished', '2019-01-10', 'winter', 'CloverWorks', 'Manga', 'mystery,shounen,Sci-Fi', 20, 8.7, 'Dikelilingi oleh hutan dan pintu masuk berpagar, Grace Field House dihuni oleh anak yatim piatu yang bahagia hidup bersama sebagai satu keluarga besar, dirawat oleh \"Mama\" mereka, Isabella. Meskipun mereka diharuskan untuk mengikuti tes setiap hari, anak-anak bebas untuk menghabiskan waktu mereka sesuai keinginan mereka, biasanya bermain di luar, selama mereka tidak terlalu jauh dari panti asuhan Ã¢â‚¬â€ peraturan yang diharapkan mereka ikuti tidak peduli apapun yang terjadi. Namun, semua masa indah harus berakhir, karena setiap beberapa bulan, seorang anak diadopsi dan dikirim untuk tinggal bersama keluarga baru mereka ... tidak pernah terdengar lagi.\r\n\r\nNamun, ketiga bersaudara tertua memiliki kecurigaan tentang apa yang sebenarnya terjadi di panti asuhan, dan mereka akan menemukan nasib kejam yang menanti anak-anak yang tinggal di Grace Field, termasuk sifat memutarbalikkan Mama tercinta mereka.', 'Yakusoku no Neverland.jpg'),
(67, 'Majo no Tabitabi', 'tv', 12, 'ongoing', '2020-10-02', 'fall', 'C2C', 'Light novel', 'adventure,fantasy,magic', 20, 7.6, 'Dahulu kala, ada seorang penyihir bernama Elaina, yang memulai perjalanan keliling dunia. Sepanjang jalan, dia akan bertemu dengan semua jenis orang, dari negara yang penuh dengan penyihir hingga raksasa yang mencintai ototnya sendiri Ã¢â‚¬â€ tetapi dengan setiap pertemuan, Elaina akan menjadi bagian kecil dari cerita mereka, dan dunianya sendiri akan mendapatkan sedikit lebih besar.', 'Majo no Tabitabi The Journey of Elaina.jpg'),
(69, 'Shingeki no Kyojin', 'tv', 25, 'ongoing', '2013-04-07', 'spring', 'WitStudio', 'Manga', 'fantasy,drama,mystery,shounen,action', 20, 8.5, 'Berabad-abad yang lalu, umat manusia dibantai hingga hampir punah oleh makhluk humanoid mengerikan yang disebut titan, memaksa manusia untuk bersembunyi dalam ketakutan di balik dinding konsentris yang sangat besar. Apa yang membuat raksasa-raksasa ini benar-benar menakutkan adalah bahwa selera mereka terhadap daging manusia tidak lahir dari rasa lapar, tetapi apa yang tampak seperti kesenangan. Untuk memastikan kelangsungan hidup mereka, sisa-sisa umat manusia mulai hidup dalam penghalang pertahanan, menghasilkan seratus tahun tanpa satupun pertemuan titan. Namun, ketenangan yang rapuh itu segera hancur ketika raksasa raksasa berhasil menembus tembok luar yang seharusnya tak tertembus, menyalakan kembali perjuangan untuk bertahan hidup melawan kekejian pemakan manusia.\r\n\r\nSetelah menyaksikan kehilangan pribadi yang mengerikan di tangan makhluk-makhluk yang menyerang, Eren Yeager mendedikasikan hidupnya untuk pemberantasan mereka dengan mendaftar ke Survey Corps, sebuah unit militer elit yang memerangi humanoid tanpa ampun di luar perlindungan tembok. Berdasarkan manga pemenang penghargaan Hajime Isayama, Shingeki no Kyojin mengikuti Eren, bersama dengan saudara perempuan angkatnya Mikasa Ackerman dan teman masa kecilnya Armin Arlert, saat mereka bergabung dalam perang brutal melawan para raksasa dan berlomba untuk menemukan cara mengalahkan mereka sebelum yang terakhir. dindingnya rusak', 'shingeki no kyoujin.jpg'),
(70, 'Boku no Hero Academia', 'tv', 13, 'finished', '2016-04-03', 'spring', 'Bones', 'Manga', 'comedy,school,shounen,action,Super Power', 20, 8.1, 'Munculnya &quot;quirks&quot;, kekuatan super yang baru ditemukan, terus meningkat selama bertahun-tahun, dengan 80 persen manusia memiliki berbagai kemampuan mulai dari manipulasi elemen hingga pengubahan bentuk. Ini membuat sisa dunia benar-benar tidak berdaya, dan Izuku Midoriya adalah salah satunya.\r\n\r\nSejak dia masih kecil, anak sekolah menengah yang ambisius itu tidak menginginkan apa pun selain menjadi pahlawan. Nasib Izuku yang tidak adil membuat dia mengagumi para pahlawan dan mencatatnya kapan pun dia bisa. Tapi tampaknya kegigihannya telah membuahkan hasil: Izuku bertemu dengan pahlawan nomor satu dan idola pribadinya, All Might. Keunikan All Might adalah kemampuan unik yang dapat diwariskan, dan dia telah memilih Izuku untuk menjadi penggantinya!\r\n\r\nBertahan selama berbulan-bulan menjalani pelatihan yang melelahkan, Izuku mendaftar di UA High, sebuah sekolah menengah bergengsi yang terkenal dengan program pelatihan pahlawannya yang luar biasa, dan mahasiswa baru tahun ini terlihat sangat menjanjikan. Dengan teman sekelasnya yang aneh tapi berbakat dan ancaman yang membayangi organisasi jahat, Izuku akan segera belajar apa artinya menjadi pahlawan', 'Boku no Hero Academia.jpg'),
(71, 'Jujutsu Kaisen', 'tv', 24, 'ongoing', '2020-10-03', 'fall', 'MAPPA', 'Manga', 'school,shounen,supernatural,action', 20, 8.5, 'Iseng-iseng melakukan aktivitas paranormal tanpa dasar dengan Klub Gaib, siswa sekolah menengah Yuuji Itadori menghabiskan hari-harinya di ruang klub atau rumah sakit, di mana dia mengunjungi kakeknya yang terbaring di tempat tidur. Namun, gaya hidup santai ini segera berubah menjadi aneh ketika dia tanpa sadar menemukan barang terkutuk. Memicu rantai kejadian supernatural, Yuuji menemukan dirinya tiba-tiba didorong ke dunia Kutukan Ã¢â‚¬â€ makhluk mengerikan yang terbentuk dari kebencian dan kenegatifan manusia Ã¢â‚¬â€ setelah menelan benda tersebut, yang diturunkan menjadi jari milik iblis Sukuna Ryoumen, \"Raja Kutukan . \"\r\n\r\nYuuji mengalami secara langsung ancaman Kutukan ini kepada masyarakat saat ia menemukan kekuatan barunya sendiri. Diperkenalkan ke Sekolah Menengah Teknik Jujutsu Metropolitan Tokyo, dia mulai berjalan di jalan yang tidak bisa dia jalani kembali Ã¢â‚¬â€ jalur seorang penyihir Jujutsu.', 'Jujutsu Kaisen.jpg'),
(72, 'Violet Evergarden', 'tv', 13, 'finished', '2018-01-11', 'winter', 'KyotoAnimation', '8.6', 'drama,fantasy', 20, 8.6, 'Pulih dari lukanya, Violet memulai hidup baru dengan bekerja di CH Postal Services setelah berselisih dengan keluarga wali barunya. Di sana, dia menyaksikan secara kebetulan pekerjaan \"Boneka Memori Otomatis,\" amanuenses yang menuliskan pikiran dan perasaan orang menjadi kata-kata di atas kertas. Tergerak oleh gagasan tersebut, Violet mulai bekerja sebagai Boneka Memori Otomatis, perdagangan yang akan membawanya pada petualangan, yang akan membentuk kembali kehidupan kliennya dan mudah-mudahan mengarah pada penemuan diri.', 'Violet Evergarden.jpg'),
(73, 'Kuroko no Basuke', 'tv', 25, 'finished', '2012-04-08', 'spring', 'ProductionIG', 'Manga', 'comedy,school,shounen', 20, 8.2, 'Tim bola basket Sekolah Menengah Pertama Teikou dinobatkan sebagai juara tiga tahun berturut-turut berkat lima pemain luar biasa yang, dengan keterampilan mereka yang menakjubkan dan unik, membuat lawan putus asa dan membuat kagum penggemar. Namun, setelah lulus, rekan satu tim ini, yang dikenal sebagai &quot;Generasi Keajaiban&quot;, berpisah dan sekarang menganggap satu sama lain sebagai saingan.\r\n\r\nDi SMA Seirin, dua mahasiswa baru yang baru direkrut membuktikan bahwa mereka bukan pemain bola basket biasa: Taiga Kagami, pemain yang menjanjikan kembali dari AS, dan Tetsuya Kuroko, seorang siswa yang tampaknya biasa yang kurangnya kehadiran memungkinkan dia untuk bergerak tanpa disadari. Meskipun Kuroko tidak atletis atau tidak mampu mencetak poin, dia adalah anggota tim bola basket Teikou, di mana dia bermain sebagai &quot;Phantom Sixth Man,&quot; yang dengan mudah mengoper bola dan membantu rekan satu timnya.\r\n\r\nKuroko no Basket mengikuti perjalanan para pemain Seirin saat mereka berusaha menjadi tim sekolah menengah Jepang terbaik dengan memenangkan Kejuaraan Interhigh. Untuk mencapai tujuan mereka, mereka harus berpapasan dengan beberapa tim yang kuat, beberapa di antaranya memiliki salah satu dari lima pemain dengan kemampuan seperti dewa, yang membuat perjanjian untuk dikalahkan oleh Kuroko dan Taiga.', 'Kuroko no Basuke.jpg'),
(74, 'Kimetsu no Yaiba', 'tv', 26, 'finished', '2019-04-06', 'spring', 'ufotable', 'Manga', 'shounen,supernatural,action', 20, 8.7, 'Sejak kematian ayahnya, beban menghidupi keluarga telah jatuh ke pundak Tanjirou Kamado. Meskipun hidup miskin di pegunungan terpencil, keluarga Kamado dapat menikmati kehidupan yang relatif damai dan bahagia. Suatu hari, Tanjirou memutuskan untuk pergi ke desa setempat untuk menghasilkan sedikit uang dengan menjual arang. Dalam perjalanan pulang, malam tiba, memaksa Tanjirou untuk berlindung di rumah orang asing, yang memperingatkannya tentang keberadaan setan pemakan daging yang mengintai di hutan pada malam hari.\r\n\r\nKetika dia akhirnya kembali ke rumah keesokan harinya, dia bertemu dengan pemandangan yang mengerikan Ã¢â‚¬â€ seluruh keluarganya telah dibantai. Lebih buruk lagi, satu-satunya yang selamat adalah saudara perempuannya, Nezuko, yang telah berubah menjadi iblis yang haus darah. Dikonsumsi oleh amarah dan kebencian, Tanjirou bersumpah untuk membalaskan dendam keluarganya dan tinggal dengan satu-satunya saudara kandungnya yang tersisa. Bersamaan dengan kelompok misterius yang menamakan diri mereka Korps Pembunuh Iblis, Tanjirou akan melakukan apa pun untuk membunuh iblis dan melindungi sisa-sisa kemanusiaan saudara perempuan tercintanya.', 'Kimetsu no Yaiba.jpg'),
(75, 'Dragon Ball Super', 'tv', 131, 'finished', '2015-07-05', 'summer', 'ToeiAnimation', 'Manga', 'adventure,comedy,fantasy,shounen,action,Super Power', 20, 7.5, 'Tujuh tahun setelah peristiwa Dragon Ball Z, Bumi damai, dan penduduknya hidup bebas dari bahaya apa pun yang mengintai di alam semesta. Namun, perdamaian ini berumur pendek; kejahatan tidur terbangun di jangkauan gelap galaksi: Beerus, Dewa Penghancur yang kejam.\r\n\r\nTerganggu oleh ramalan bahwa dia akan dikalahkan oleh \"Dewa Super Saiyan,\" Beerus dan malaikat pengiringnya Whis mulai mencari alam semesta untuk makhluk misterius ini. Tak lama kemudian, mereka mencapai Bumi di mana mereka bertemu Gokuu Son, salah satu pejuang terkuat di planet ini, dan teman-temannya yang sama kuatnya', 'Dragon Ball Super.jpg'),
(76, 'Mahouka Koukou no Rettousei', 'tv', 26, 'finished', '2014-04-06', 'spring', 'Madhouse', 'Light novel', 'romance,magic,school,supernatural,action,Sci-Fi', 20, 7.6, '	\r\nPada awal abad ke-21, sihir, yang telah lama dianggap sebagai cerita rakyat dan dongeng, telah menjadi teknologi yang tersistematisasi dan diajarkan sebagai keterampilan teknis. Di Sekolah Menengah Pertama, institusi untuk pesulap, siswa dipisahkan menjadi dua kelompok berdasarkan nilai ujian masuk mereka: \"Blooms,\" mereka yang menerima nilai tinggi, ditugaskan ke Kursus Pertama, sedangkan \"Weeds\" adalah siswa cadangan yang ditugaskan ke Kursus kedua.\r\n\r\nMahouka Koukou no Rettousei mengikuti saudara kandungnya, Tatsuya dan Miyuki Shiba, yang terdaftar di Sekolah Menengah Pertama. Setelah mengikuti ujian, Miyuki yang luar biasa ditempatkan di Kursus Pertama, sementara Tatsuya diturunkan ke Kursus Kedua. Meskipun nilai ujian praktis dan statusnya sebagai \"Weed\" menunjukkan dia tidak kompeten secara sihir, dia memiliki pengetahuan teknis yang luar biasa, kemampuan tempur fisik, dan teknik sihir yang unik Ã¢â‚¬â€ membuat Tatsuya menjadi orang yang tidak biasa di sekolah menengah sihir.', 'Mahouka Koukou no Rettousei.jpg'),
(77, 'Naruto', 'tv', 220, 'finished', '2002-10-03', 'fall', 'Pierrot', 'Manga', 'adventure,comedy,shounen,action,Super Power', 20, 7.9, 'Beberapa saat sebelum kelahiran Naruto Uzumaki, iblis besar yang dikenal sebagai Kyuubi, Rubah Ekor Sembilan, menyerang Konohagakure, Desa Daun Tersembunyi, dan membuat kekacauan. Untuk mengakhiri amukan Kyuubi, pemimpin desa, Hokage Keempat, mengorbankan hidupnya dan menyegel monster mengerikan di dalam tubuh Naruto yang baru lahir.\r\n\r\nSekarang, Naruto adalah ninja hiperaktif dan berkepala bulat yang masih tinggal di Konohagakure. Dijauhi karena Kyuubi di dalam dirinya, Naruto berjuang untuk menemukan tempatnya di desa, sementara keinginan membara untuk menjadi Hokage Konohagakure membawanya tidak hanya ke beberapa teman baru yang hebat, tetapi juga beberapa musuh yang mematikan.', 'Naruto.jpg'),
(78, 'Sword Art Online', 'tv', 25, 'finished', '2012-07-08', 'summer', 'A1Pictures', 'Light novel', 'romance,adventure,fantasy,game,action', 20, 7.3, 'Pada tahun 2022, realitas virtual telah berkembang pesat, dan permainan peran online besar-besaran yang disebut Sword Art Online (SAO) diluncurkan. Dengan bantuan teknologi \"NerveGear\", pemain dapat mengontrol avatar mereka di dalam game hanya menggunakan pikiran mereka sendiri.\r\n\r\nKazuto Kirigaya, yang dijuluki \"Kirito,\" adalah salah satu dari sedikit penggemar yang beruntung yang mendapatkan pengiriman pertama dari game tersebut. Dia masuk untuk menemukan dirinya, bersama sepuluh ribu orang lainnya, di dunia Aincrad yang indah dan rumit, yang penuh dengan senjata abad pertengahan yang fantastis dan monster yang mengerikan. Namun, dalam pergantian peristiwa yang kejam, para pemain segera menyadari bahwa mereka tidak dapat keluar; pencipta game telah menjebak mereka di dunia barunya hingga mereka menyelesaikan semua seratus level game.\r\n\r\nUntuk melarikan diri dari Aincrad, Kirito sekarang harus berinteraksi dan bekerja sama dengan sesama pemain. Beberapa adalah sekutu, sementara yang lain adalah musuh, seperti Asuna Yuuki, yang memimpin kelompok utama yang mencoba melarikan diri dari permainan yang kejam. Lebih buruk lagi, Sword Art Online tidak semuanya menyenangkan dan permainan: jika mereka mati di Aincrad, mereka mati dalam kehidupan nyata. Kirito harus beradaptasi dengan realitas barunya, berjuang untuk bertahan hidup, dan semoga terbebas dari neraka virtualnya.', 'Sword Art Online.jpg'),
(79, 'Re:Zero kara Hajimeru Isekai Seikatsu', 'tv', 25, 'finished', '2016-04-04', 'spring', 'WhiteFox', 'Light novel', 'drama,fantasy', 20, 8.3, 'Ketika Subaru Natsuki meninggalkan toko swalayan, hal terakhir yang dia harapkan adalah terenggut dari kehidupan sehari-harinya dan jatuh ke dunia fantasi. Hal-hal tidak terlihat baik bagi remaja yang kebingungan; Namun, tidak lama setelah kedatangannya, dia diserang oleh beberapa preman. Berbekal hanya tas belanjaan dan ponsel yang sekarang tidak berguna, dia dengan cepat dipukuli sampai habis. Untungnya, seorang wanita cantik misterius bernama Satella, dalam pengejaran setelah orang yang mencuri lambangnya, terjadi pada Subaru dan menyelamatkannya. Untuk berterima kasih kepada gadis yang jujur Ã¢â‚¬â€¹Ã¢â‚¬â€¹dan baik hati, Subaru menawarkan bantuan dalam pencariannya, dan kemudian malam itu, dia bahkan menemukan keberadaan apa yang dia cari. Tapi tanpa sepengetahuan mereka, kekuatan yang jauh lebih gelap mengintai pasangan itu dari bayang-bayang, dan hanya beberapa menit setelah menemukan lambang, Subaru dan Satella dibunuh secara brutal.\r\n\r\nNamun, Subaru segera terbangun kembali ke adegan yang sudah dikenalnya Ã¢â‚¬â€ dihadapkan oleh kelompok preman yang sama, bertemu Satella lagi Ã¢â‚¬â€ teka-teki itu semakin dalam saat sejarah berulang tanpa bisa dijelaskan.', 'Re Zero kara Hajimeru Isekai Seikatsu.jpg'),
(80, 'Tate no Yuusha no Nariagari', 'tv', 25, 'finished', '2019-01-09', 'winter', 'KinemaCitrus', 'Light novel', 'adventure,drama,fantasy,action', 20, 8, 'Empat Pahlawan Kardinal adalah sekelompok orang biasa dari Jepang modern yang dipanggil ke kerajaan Melromarc untuk menjadi penyelamatnya. Melromarc adalah negara yang dilanda Gelombang Malapetaka yang telah berulang kali meluluhlantahkan tanah dan membawa bencana bagi warganya selama berabad-abad. Keempat hero tersebut masing-masing dianugerahi pedang, tombak, busur, dan perisai untuk menaklukkan Gelombang tersebut. Naofumi Iwatani, seorang otaku, dikutuk dengan takdir menjadi \"Pahlawan Perisai\". Berbekal hanya perisai yang sangat kecil, Naofumi diremehkan dan diejek oleh sesama pahlawan dan orang-orang kerajaan karena kemampuan serangannya yang lemah dan kepribadian yang tidak bersemangat.\r\n\r\nKetika para pahlawan diberikan sumber daya dan rekan untuk berlatih, Naofumi berangkat dengan satu-satunya orang yang bersedia berlatih bersamanya, Malty Melromarc. Dia segera dikhianati olehnya, bagaimanapun, dan dituduh mengambil keuntungan darinya. Naofumi kemudian menjadi sangat didiskriminasi dan dibenci oleh orang-orang Melromarc untuk sesuatu yang tidak dia lakukan. Dengan badai rasa sakit yang mengamuk dan ketidakpercayaan di dalam hatinya, Naofumi memulai perjalanannya untuk memperkuat dirinya dan reputasinya. Lebih jauh lagi, kesulitan berada di setnya sendiri, jadi Naofumi membeli seorang budak demi-human di ambang kematian bernama Raphtalia untuk menemaninya dalam perjalanannya.\r\n\r\nSaat Gelombang mendekati kerajaan, Naofumi dan Raphtalia harus berjuang untuk kelangsungan hidup kerajaan dan melindungi orang-orang Melromarc dari masa depan naas mereka.', 'Tate no Yuusha no Nariagari.jpg'),
(81, 'Saiki Kusuo no ÃŽÂ¨-nan', 'tv', 120, 'finished', '2016-07-04', 'summer', 'JCStaff', 'Manga', 'comedy,school,shounen,supernatural', 20, 8.5, 'Bagi kebanyakan orang, kemampuan psikis mungkin tampak seperti berkah; bagi Kusuo Saiki, bagaimanapun, ini tidak bisa jauh dari kebenaran. Diberkahi dengan berbagai macam kemampuan supernatural mulai dari telepati hingga penglihatan x-ray, dia menemukan apa yang disebut berkah ini hanyalah kutukan. Karena semua ketidaknyamanan yang ditimbulkan oleh kekuatannya terus-menerus menumpuk, semua tujuan Kusuo adalah kehidupan yang biasa dan tanpa kerumitan Ã¢â‚¬â€ kehidupan di mana ketidaktahuan adalah kebahagiaan.\r\n\r\nSayangnya, kehidupan seorang paranormal jauh dari ketenangan. Meskipun Kusuo mencoba untuk tetap berada di luar sorotan dengan merahasiakan kekuatannya dari teman-teman sekelasnya, dia akhirnya secara tidak sengaja menarik perhatian banyak karakter aneh, seperti Riki Nendou yang berkepala kosong dan Shun Kaidou yang berkhayal. Dipaksa untuk menghadapi kegilaan orang-orang di sekitarnya, Kusuo mengetahui bahwa kehidupan biasa yang dia perjuangkan jauh lebih sulit untuk dicapai daripada yang diharapkan.', 'Saiki Kusuo no Î¨-nan.jpg'),
(82, 'Boruto: Naruto Next Generations', 'tv', 178, 'ongoing', '2017-04-05', 'spring', 'Pierrot', 'Manga', 'adventure,shounen,action,Super Power', 20, 5.9, 'Setelah berakhirnya Perang Dunia Shinobi Keempat, Konohagakure telah menikmati masa damai, kemakmuran, dan kemajuan teknologi yang luar biasa. Ini semua berkat upaya Pasukan Aliansi Shinobi dan Hokage Ketujuh desa, Naruto Uzumaki. Kini menyerupai kota metropolis modern, Konohagakure telah berubah, terutama kehidupan seorang shinobi. Di bawah pengawasan Naruto dan rekan-rekan lamanya, generasi baru shinobi telah melangkah untuk mempelajari cara-cara ninja.\r\n\r\nBoruto Uzumaki sering menjadi pusat perhatian sebagai anak dari Hokage Ketujuh. Meskipun mewarisi sikap Naruto yang keras dan keras kepala, Boruto dianggap sebagai anak ajaib dan mampu mengeluarkan potensinya dengan bantuan teman dan keluarga yang mendukung. Sayangnya, ini hanya memperburuk kesombongannya dan keinginannya untuk melampaui Naruto yang, bersama dengan gaya hidup ayahnya yang sibuk, telah membuat tegang hubungan mereka. Namun, kekuatan jahat yang muncul di dalam desa dapat mengancam kehidupan Boruto yang tanpa beban.\r\n\r\nTeman baru dan wajah akrab bergabung dengan Boruto saat cerita baru dimulai di Boruto: Naruto Next Generations.\r\n', 'Boruto.jpg'),
(83, 'Maou Gakuin no Futekigousha', 'tv', 13, 'finished', '2020-07-04', 'summer', 'SilverLink', 'Manga', 'fantasy,magic,school,action', 20, 7.4, 'Di masa lalu, perang antara manusia dan iblis menyebabkan kekacauan dan pertumpahan darah yang meluas. Untuk mengakhiri konflik yang tampaknya tak berujung ini, Raja Iblis Anos Voldigoad rela mengorbankan hidupnya, berharap terlahir kembali di masa depan yang damai.\r\n\r\nDalam persiapan untuk kembalinya raja mereka, ras iblis menciptakan Akademi Raja Iblis, sebuah institusi elit yang bertugas menentukan identitas Anos ketika dia bangun kembali. Dia bereinkarnasi dua milenium kemudian, tetapi yang mengejutkan, dia segera mengetahui bahwa tingkat sihir di dunia telah berkurang drastis selama ketidakhadirannya. Selain itu, ketika dia mendaftar di akademi untuk mendapatkan kembali gelarnya yang sah, dia mengetahui bahwa iblis mengingatnya secara berbeda. Kepribadiannya, perbuatannya, dan bahkan warisannya semuanya dipalsukan Ã¢â‚¬â€ bertopeng di bawah nama penipu. \"Kurangnya\" pengetahuan umum ini membuatnya menjadi orang asing di akademi Ã¢â‚¬â€ ketidakcocokan yang belum pernah terlihat dalam sejarah.\r\n\r\nTerlepas dari kekurangan ini, Anos tetap tidak terpengaruh. Saat dia berusaha mengungkap mereka yang mengubah masa lalunya yang gemilang, dia mengambil alih untuk membuat keturunannya menyadari bahwa penguasa mereka akhirnya telah kembali.', 'Maou Gakuin no Futekigousha.jpg'),
(84, 'The God of High School', 'tv', 13, 'finished', '2020-07-06', 'summer', 'MAPPA', 'Manga Web', 'adventure,comedy,fantasy,supernatural,action,Sci-Fi', 20, 7.2, 'Turnamen &quot;God of High School&quot; telah dimulai, mencari petarung terhebat di antara siswa SMA Korea! Semua gaya seni bela diri, senjata, sarana, dan metode untuk meraih kemenangan diizinkan. Hadiah? Satu keinginan untuk apapun yang diinginkan oleh pemenang.\r\n\r\nPakar Taekwondo Jin Mo-Ri diundang untuk berpartisipasi dalam kompetisi. Di sana dia berteman dengan spesialis karate Han Dae-Wi dan pendekar pedang Yu Mi-Ra, yang keduanya masuk karena alasan pribadi mereka sendiri. Mo-Ri tahu bahwa tidak ada lawan yang sama dan bahwa pertandingan akan menjadi yang paling kejam yang pernah dia lawan dalam hidupnya. Tapi bukannya khawatir, prospek ini membuatnya semakin bersemangat.\r\n\r\nSebuah rahasia terletak di balik topeng tes transparan dari kecakapan bertarung yang diklaim turnamen tersebut Ã¢â‚¬â€ salah satu yang membuat kandidat politik Korea Park Mu-Jin menonton setiap pertarungan dengan mata lapar dan penuh harap. Mo-Ri, Dae-Wi, dan Mi-Ra akan menemukan apa artinya menjadi Dewa Sekolah Menengah.', 'The God of High School.jpg'),
(85, 'Toaru Majutsu no Index ', 'tv', 24, 'finished', '2008-10-05', 'fall', 'JCStaff', 'Light novel', 'magic,action,Sci-Fi,Super Power', 20, 7.5, 'Academy City, Jepang, berada di garis depan sains. Selain 30 tahun lebih maju dari dunia teknologi, lebih dari tiga perempat penduduk kota aneh ini terdiri dari pelajar yang mengembangkan kemampuan psikisnya sebagai esper di berbagai institusi. Di antara siswa ini adalah Touma Kamijou, seorang siswa sekolah menengah dengan pangkat psikis terendah nol, tetapi dengan kekuatan misterius tidak ada ilmuwan yang dapat memahami: &quot;Imagine Breaker,&quot; yang memungkinkan dia untuk meniadakan kemampuan supernatural lainnya.\r\n\r\nIni, bagaimanapun, tidak mempengaruhi kehidupan Kamijou sedikitpun saat dia memainkan perannya sebagai remaja biasa; yaitu, sampai dia bertemu dengan Index Librorum Prohibitorum yang aneh, seorang gadis muda yang telah menghafal seluruh grimoire terlarang, dan sekarang sebuah organisasi berbahaya sedang memburu Index. Dengan beberapa penyihir yang ingin melukai gadis itu, Kamijou akan membela teman barunya dengan segala cara saat dia menemukan dunia baru yang aneh dari supernatural.', 'Toaru Majutsu no Index.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `studios`
--

CREATE TABLE `studios` (
  `studios` varchar(100) NOT NULL,
  `industri` varchar(50) NOT NULL,
  `didirikan` date NOT NULL,
  `kantor` varchar(255) NOT NULL,
  `deskripsi` text NOT NULL,
  `karyawan` int(11) NOT NULL,
  `situs` varchar(255) NOT NULL,
  `gambarstudio` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `studios`
--

INSERT INTO `studios` (`studios`, `industri`, `didirikan`, `kantor`, `deskripsi`, `karyawan`, `situs`, `gambarstudio`) VALUES
('A1Pictures', 'Anime', '2005-05-09', 'Tokyo', 'A-1 Pictures Inc. adalah sebuah studio animasi Jepang yang didirikan oleh eks-produser Sunrise Mikihiro Iwata, sebuah cabang dari firma produksi anime Sony Music Entertainment (Jepang) Aniplex.[3][4]', 152, 'www.a1p.jp', 'A-1 Pictures.png'),
('Bones', 'Anime', '1998-10-01', 'Tokyo', 'Bones Inc. (Hepburn: Kabushiki-gaisha Bonzu) adalah sebuah studio anime Jepang. Bones telah memproduksi banyak seri, termasuk Noragami, Wolf\'s Rain, Scrapped Princess, Eureka Seven, Angelic Layer, Darker than Black, Soul Eater, Ouran High School Host Club dan dua adaptasi dari manga Fullmetal Alchemist bersama dengan Star Driver, Gosick, Mob Psycho 100, Space Dandy, dan My Hero Academia. Kantor pusatnya berlokasi di Igusa, Suginami, Tokyo.[1]', 110, 'www.bones.co.jp', 'bones.jpg'),
('C2C', 'Anime', '2006-04-03', 'Tokyo', 'C2C Co., Ltd. (C2C Kabushiki-gaisha C2C) adalah studio animasi Jepang yang didirikan pada tanggal 3 April 2006.', 100, 'www.c2c2009.com/en', 'C2C.png'),
('CloverWorks', 'Studio animasi', '2018-10-01', 'Tokyo', 'Pada bulan April 2018, A-1 Pictures melakukan pemerekan ulang Studio K?enji mereka sebagai CloverWorks yang memiliki ciri khas tersendiri, terpisah dari Studio Asagaya yang merupakan studio utama mereka.[4][5] Studio ini berpusat di di Suginami, Tokyo.[2]\r\n\r\nEmpat seri animasi telah beralih studio dari A-1 Pictures ke CloverWorks setelah pemerekan ulang. Beberapa seri anime tersebut masing-masing adalah Slow Start, Darling in the Franxx, Persona 5: The Animation dan Ace Attorney Season 2. Slow Start beralih studio setelah musim pertamanya usai, sedangkan Darling in the Franxx beralih studio mulai 12 episode terakhir.[6][7]\r\n\r\nPada tanggal 1 Oktober 2018, CloverWorks mengumumkan bahwa mereka telah berpisah dari A-1 Pictures, meskipun mereka masih merupakan anak perusahaan dari Aniplex.[3] Hari itu juga menandai tanggal pendirian dari studio tersebut.[2]', 55, 'cloverworks.co.jp', 'cloverworks.jpg'),
('Gokumi', 'Studio animasi Jepang', '2010-05-09', 'Tokyo', 'Studio Gokumi Co., Ltd. (Hepburn: Kabushiki-gaisha Sutaijo Gokumi) adalah sebuah studio animasi Jepang yang didirikan oleh para mantan anggota Gonzo.[3]', 90, 'www.gokumi.co.jp', 'Gokumi.png'),
('JCStaff', 'Anime', '1986-01-06', 'Tokyo', 'J.C.Staff Co., Ltd. Kabushiki gaisha J? Sh? Sutaffu, J dan C berarti \"Japan Creative\"), adalah sebuah studio animasi Jepang yang didirikan pada bulan Januari 1986 oleh Tomoyuki Miyata, yang sebelumnya bekerja di Tatsunoko Production. Karya pertama studio ini adalah Y?t?den pada tahun 1987. Mereka telah memproduksi beberapa seri anime yang terkenal, seperti Slayers, Revolutionary Girl Utena, Excel Saga, Alien Nine, Azumanga Daioh, Ikki T?sen: Battle Vixens, Shingetsutan Tsukihime, Honey and Clover, Shakugan no Shana, The Familiar of Zero, Toradora!, A Certain Magical Index, A Certain Scientific Railgun, Maid Sama!, The Pet Girl of Sakurasou, and Food Wars!: Shokugeki no Soma. Sejak tahun 2005, sebagian besar karya mereka disutradarai oleh Takashi Watanabe, Ken\'ichi Kasai dan Yoshiaki Iwasaki.', 162, 'www.jcstaff.co.jp', 'J.C.Staff.png'),
('KinemaCitrus', 'Studio animasi', '2008-03-03', 'Tokyo', 'Kinema Citrus Co., Ltd. (Kabushiki-gaisha Kinema Shitorasu) adalah sebuah studio animasi Jepang yang didirikan pada tanggal 3 Maret 2008 oleh mantan staf Production I.G dan Bones yang berpusat di Suginami, Tokyo. Karya-karya terkenal mereka antara lain adalah Tokyo Magnitude 8.0 pada tahun 2009 yang diproduksi bersama dengan Bones, .hack//Quantum, sebuah seri OVA berjumlah 3 episode, Black Bullet dan Barakamon pada tahun 2014, serta Made in Abyss pada tahun 2017.', 69, 'kinemacitrus.biz', 'Kinema Citrus.png'),
('KyotoAnimation', 'Animasi Jepang Novel ringan', '1981-01-06', 'Tokyo', 'Kyoto Animation Co., Ltd. (Kabushiki-gaisha Ky?to Anim?shon), disingkat menjadi KyoAni (???), adalah sebuah studio animasi Jepang sekaligus penerbit novel ringan yang berpusat di Uji, Prefektur Kyoto, Jepang. Perusahaan ini didirikan pada tahun 1981 oleh mantan staf Mushi Pro. Dipimpin oleh Hideaki Hatta, perusahaan ini juga berafiliasi dengan studio Animation Do. Hingga tahun 2015, Kyoto Animation telah memimpin produksi untuk 21 seri anime dan beberapa film. Para juru animasi dari Kyoto Animation merupakan pekerja yang digaji, alih-alih juru animasi paruh waktu yang dibayar per bingkai (frame). Dengan demikian, para juru animasi Kyoto Animation lebih mampu untuk fokus pada kualitas dari masing-masing bingkai daripada kuantitas bingkai yang mereka produksi.[6]\r\n\r\nPada tanggal 18 Juli 2019, kebakaran terjadi di studio utama Kyoto Animation. Dilaporkan 34 orang meninggal, 30 orang luka-luka dan 10 orang kritis akibat kejadian tersebut. Satu orang diamankan karena sebelumnya ia terlihat menyiramkan bensin di sekitar studio Kyoto Animation.[7][8][9]', 130, 'www.kyotoanimation.co.jp', 'kyotoanimation.png'),
('Madhouse', 'animasi', '1972-05-01', 'Tokyo', 'MADHOUSE Inc. (Kabushiki-gaisha Maddohausu) adalah sebuah studio animasi Jepang yang didirikan pada tahun 1972 oleh beberapa bekas animator Mushi Pro, termasuk Masao Maruyama, Osamu Dezaki, Rintaro, dan Yoshiaki Kawajiri. Karya pertama Madhouse adalah seri animasi Ace o Nerae! (1973).\r\n\r\nMadhouse pernah memproduksi OVA pada akhir 1980-an dan awal 1990-an, tetapi lebih dikenal lewat seri animasi televisi dan film animasi layar lebarnya. Antara film layar lebar produksi Madhouse adalah Metropolis dan film-film karya Satoshi Kon: Perfect Blue, Millennium Actress, Tokyo Godfathers, dan Paprika.', 150, 'http://www.madhouse.co.jp/', 'Madhouse.png'),
('MAPPA', 'Anime', '2011-07-14', 'Tokyo', 'MAPPA Co., Ltd. (MAPPA Hepburn: Kabushiki-gaisha Mappa) adalah sebuah studio animasi asal Jepang yang didirikan pada tahun 2011 oleh Masao Maruyama, pendiri dan mantan produser Madhouse.[1][2]\r\n\r\n\"MAPPA\" merupakan akronim dari Maruyama Animation Produce Project Association.[3] Pada bulan April 2016, Maruyama mundur dari posisinya di MAPPA dan mendirikan studio baru, Studio M2.[4]', 200, 'http://mappa.co.jp/', 'MAPPA.png'),
('Pierrot', 'Media dan Hiburan', '1979-05-01', 'Tokyo', 'Pierrot Co., Ltd. (Kabushiki-gaisha Piero) merupakan sebuah studio animasi Jepang, sejak tahun 1979 oleh mantan karyawan Tatsunoko Production dan Mushi Production. Kantor pusatnya terletak di Mitaka, Tokyo.[1]\r\n\r\nPerusahaan ini memiliki logo sederhana dari wajah badut. \"Piero\" merupakan kata serapan bahasa Jepang untuk badut, diadopsi dari karakter klasik Pierrot.\r\n\r\nYuYu Hakusho dan Saiyuki, dua seri anime perusahaan ini, memenangkan Animage Anime Grand Prix Award pada tahun 1993 dan 2000.', 190, 'en.pierrot.jp', 'Pierrot.png'),
('ProductionIG', 'Anime, Film, Siaran Televisi, Permainan Video', '1987-12-15', 'Tokyo', 'Production I.G (Kabushiki-gaisha Purodakushon Ai J?) adalah sebuah perusahaan studio dan produksi anime Jepang, yang didirikan pada 15 Desember 1987 oleh Mitsuhisa Ishikawa. Perusahaan ini berkantor pusat di Musashino, Tokyo, Tokyo, Jepang.[2]\r\n\r\nProduction I.G telah terlibat dalam produksi beberapa serial televisi anime, animasi video asli (OVA), film, cut-scene animasi permainan video, perancangan dan pengembangan permainan video, termasuk penerbitan dan manajemen musik. Karya-karyanya yang terkenal antara lain serial Psycho-Pass dan Ghost in the Shell.\r\n\r\nProduction I.G juga dikenal dalam dunia permainan video karena membantu pengembangan intro dan ilustrasi untuk permainan-permainan video, seperti produksi Namco Tales Studio yang terkenal, Tales of Symphonia.\r\n\r\nHuruf I dan G pada nama perusahaan ini berasal dari nama dua pendirinya, Mitsuhisa Ishikawa dan desainer karakter populer, Takayuki Goto.[2]\r\n\r\nProduction I.G termasuk anggota Asosiasi Animasi Jepang/The Association of Japanese Animations (AJA) (Nippon Douga Kyoukai).', 120, 'www.production-ig.co.jp', 'Production IG.png'),
('SilverLink', 'Studio animasi', '2007-12-03', 'Tokyo', 'SILVER LINK., Inc. (Hepburn: Kabushiki gaisha Shirub? Rinku) adalah studio animasi Jepang. Didirikan oleh produser animasi Hayato Kaneko pada Desember 2007 dan bertempat di Tokyo. Mayoritas produksi solo Silver Link telah disutradarai oleh Shin ?numa, yang sebelumnya adalah asisten sutradara bersama Akiyuki Shinbo di Shaft.', 130, 'www.silverlink.co.jp', 'Silver Link.png'),
('ToeiAnimation', 'Studio animasi dan perusahaan produksi', '1948-01-23', 'Tokyo', 'Toei Animation (T?ei Anim?shon) (JASDAQ: 4816) adalah nama sebuah studio animasi Jepang yang dimiliki oleh perusahaan Toei Company. Studio animasi ini didirikan tahun 1956, dan sejak saat itu Toei sudah memproduksi berbagai judul film animasi.\r\n\r\nFilm animasi pertama di Toei Animation adalah The White Snake Enchantress (Hakuja-Den, 1958), dan serial anime pertama di studio ini adalah Ookami Shonen Ken (1963). Pada tahun 1966, Toei Animation mulai memproduksi serial anime karya Shotaro Ishinomori, seperti Rainbow Sentai Robin, Kaizoku Ouji, Cyborg 009, dan Genshi Shounen Ryuu. Sejak tahun 1972, Toei Animation memproduksi serial anime karya Go Nagai, termasuk Devilman, Mazinger Z, Cutey Honey, dan UFO Robot Grendizer.\r\n\r\nStudio ini sebelumnya dikenal dengan nama Toei Doga (T?ei D?ga) hingga tahun 1998 sebelum akhirnya memutuskan untuk berganti nama menjadi Toei Animation.', 300, 'www.toei-anim.co.jp', 'ToeiAnimation.png'),
('Ufotable', 'Japanese animation', '2000-10-03', 'Tokyo', 'Ufotable, Inc. (Hepburn: Y?f?t?buru y?gen-gaisha) adalah studio animasi Jepang yang didirikan pada Oktober 2000 oleh mantan staf anak perusahaan TMS Entertainment Telecom Animation Film dan berlokasi di Nakano, Tokyo. Ciri khas unik yang terlihat di banyak karya mereka (Ninja Nonsense, Futakoi Alternative, Coyote Ragtime Show, Gakuen Utopia Manabi Straight !, Tales of Symphonia, The Garden of Sinners) adalah urutan claymation. Karya terkenal lainnya dari studio termasuk Fate / Zero, Fate / stay night: Unlimited Blade Works dan Demon Slayer: Kimetsu no Yaiba.\r\n\r\nPada Maret 2019, dilaporkan bahwa penggeledahan dilakukan di kantor Ufotable karena dugaan penggelapan pajak. [2] Bulan berikutnya, dilaporkan bahwa Ufotable berhutang pajak sebesar ¥ 400 juta dan diduga menyelewengkan dana dari lelang amal untuk korban gempa Tohoku 2011. Pada bulan Juni 2020, baik studio maupun pendiri dan presiden perusahaan Hikaru Kondo didakwa melanggar Undang-undang Pajak Perusahaan dan Undang-Undang Pajak Konsumsi karena gagal membayar pajak sebesar ¥ 139 juta (sekitar US $ 1,28 juta). [3] [4] Studio tersebut menerbitkan pernyataan publik yang meminta maaf atas tindakan mereka. [5]', 200, 'ufotable.com', 'Ufotable.png'),
('WhiteFox', 'Animasi Jepang', '2007-04-03', 'Tokyo', 'White Fox Co., Ltd. ( WHITE FOX Hepburn: Kabushiki gaisha Howaito Fokkusu), adalah sebuah studio animasi Jepang. Meskipun mereka termasuk studio yang masih muda dan baru memiliki sedikit karya, kebanyakan serial anime yang mereka produksi seperti Steins;Gate dan Re:Zero kara Hajimeru Isekai Seikatsu menjadi populer dan sukses secara finansial.', 133, 'w-fox.co.jp', 'White Fox.png'),
('WitStudio', 'Studio animasi', '2012-06-01', 'Tokyo', 'WIT STUDIO, Inc. (Hepburn: Kabushiki-gaisha Witto Sutajio) adalah sebuah studio animasi Jepang yang didirikan pada tanggal 1 Juni 2012 oleh para produser dari Production I.G sebagai anak perusahaan dari IG Port. Studio ini bermarkas di Musashino, Tokyo, Jepang, dan dipimpin oleh produser Production I.G, George Wada, sebagai presidennya dan Tetsuya Nakatake—juga seorang produser di Production I.G., sebagai direktur. Studio ini meraih popularitas karena telah memproduksi adaptasi anime dari seri manga Attack on Titan.[1]\r\n\r\nWit Studio didanai oleh modal awal senilai ¥30,000,000 dari IG Port, Wada dan Nakatake. Ketiga pihak memiliki saham sekitar 66.6%, 21.6% dan 10.0% di studio ini secara berurutan.[3][4]', 34, 'witstudio.co.jp', 'WitStudio.png');

-- --------------------------------------------------------

--
-- Table structure for table `user2`
--

CREATE TABLE `user2` (
  `id` int(11) NOT NULL,
  `username` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `level` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user2`
--

INSERT INTO `user2` (`id`, `username`, `password`, `level`) VALUES
(3, 'huan', '$2y$10$vIBOF9iFhpM1Ecp7XxwLUehyZQjrsTyFgy28Q6M0nzg89O9K0jGpS', 'admin'),
(4, 'user', '$2y$10$EJglTEqqV8jx/tOW.69ynu6jSdkOjyEBXBHb0ZC1NvF8mlr2jg6f.', 'user');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `anime`
--
ALTER TABLE `anime`
  ADD PRIMARY KEY (`idanime`),
  ADD KEY `studios` (`studios`);

--
-- Indexes for table `studios`
--
ALTER TABLE `studios`
  ADD PRIMARY KEY (`studios`);

--
-- Indexes for table `user2`
--
ALTER TABLE `user2`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `anime`
--
ALTER TABLE `anime`
  MODIFY `idanime` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=86;

--
-- AUTO_INCREMENT for table `user2`
--
ALTER TABLE `user2`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `anime`
--
ALTER TABLE `anime`
  ADD CONSTRAINT `anime_ibfk_1` FOREIGN KEY (`studios`) REFERENCES `studios` (`studios`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
